### ISSUE TITLE
EvoSuite error: EvoSuiteprocesserro： Exception creating connection to ${LOCAL_IP_ADDRESS}

### ISSUE THREAD

**Issue by alaahong** [JetBrains-Research/TestSpark#125]
**Describe the bug**
As computer security restricted , it will block all inbound request with almost ports by default. Which means, the computer can't visit the URI even by itself besides localhost. 

**To Reproduce**
1. Go to 'TestSpark'
2. Click on 'EvoSuite generator', whatever class or method code type.
3. Click next, see error

**Expected behavior**
Test spark can provide the configuration to change the evosuite service with localhost, not the IP. otherwise, provide a way to customized the port for evosuite service.

**Additional context**
As the exception is including specific local IP in message, so I guess that's limited by our computer inbound restriction. localhost should be fine if testspark provided such way to connect.

**Comment by pderakhshanfar** [comment]
@alaahong Thank you for opening this issue. You are right. We can at least let the user to change the default port in the settings. We will add this option in our next release (expected by end of March).
