### ISSUE TITLE
Integrating Kex into TestSpark plugin

### ISSUE THREAD

**Issue by pderakhshanfar** [JetBrains-Research/TestSpark#171]
Check the position and apply via [this link](https://internship.jetbrains.com/projects/1436/).

**Comment by Vladislav0Art** [comment]
Is this issue still relevant, and is the internship vacant?

CC: @pderakhshanfar

**Comment by pderakhshanfar** [comment]
CC: @AbdullinAM

**Comment by AbdullinAM** [comment]
Yes, we have an intern that will start working on this next week

**Comment by pderakhshanfar** [comment]
Then this comment can be closed :) Thanks @Vladislav0Art for double-checking.
