### ISSUE TITLE
EvoSuite "can not run a program"

### ISSUE THREAD

**Issue by Frosendroska** [JetBrains-Research/TestSpark#232]
**Describe the bug**

<img width="403" alt="image" src="https://github.com/JetBrains-Research/TestSpark/assets/70476032/94bd2f66-ace7-4868-b1d1-5f9ac0a06db4">

**To Reproduce**
0. Go to the branch: `development`
1. Run "Run IDE for UI Tests"
2. Right mouse click
3. TestSpark
4. Put a tick on EvoSuit and any of the line/method/class
5. My java path is `~/Library/Java/JavaVirtualMachines/corretto-11.0.23/Contents/Home/bin/java`
6. See an error

**Expected behavior**
Start EvoSuit test generation. 

**Additional context**
- [ ] Please, provide better description (in a panel where users have to paste the java path) on how the java path should look like

**Comment by Hello-zoka** [comment]
It's required to provide a full path to the Java executable. Works completely fine in this case
