### ISSUE TITLE
getSurroundingLine --> getSurroundingLineIndex

### ISSUE THREAD

**Issue by Frosendroska** [JetBrains-Research/TestSpark#235]
# Description
@Vladislav0Art [comment](https://github.com/JetBrains-Research/TestSpark/pull/223#discussion_r1623395375) to the PR 

> I think the name getSurroundingLineNumber (or getSurroundingLineIndex if the index is returned) is better; as for now, the name suggests that the method returns the actual line as String.

**Comment by Vladislav0Art** [comment]
In the comment I meant that the **current name** `getSurroundingLine` is not suitable for the function that returns an integer, and it should be renamed either to `getSurroundingLineNumber` (if line number returned) of `getSurroundingLineIndex` (if index is returned).

**Comment by Frosendroska** [comment]
Fixed in [this PR](https://github.com/JetBrains-Research/TestSpark/pull/304)
