### ISSUE TITLE
Warning panel

### ISSUE THREAD

**Issue by Frosendroska** [JetBrains-Research/TestSpark#239]
Implement a class that will allow us to show warning panels when there are some errors in the application.

As far as I am concerned, we show them then there are problems with test generation. Can we extend the same interface and reuse it for other errors? For example "Unsupported language".

**Comment by arksap2002** [comment]
`ErrorManager` interface and it's implementations

**Comment by arksap2002** [comment]
`ErrorManager` interface and it's implementations
