### ISSUE TITLE
"Modify with LLM" may insert an entire test suite into test case code editor

### ISSUE THREAD

**Issue by Vladislav0Art** [JetBrains-Research/TestSpark#252]
**Describe the bug**
I used `GPT-4o` for test generation for the following class:
```kotlin
public class Calc {
    public int sum(int a, int b) {
        return a + b; // line 3
    }

    public int multiply(int a, int b) {
        return a * b;
    }

    public int sumWithOther(Calc other, int a, int b) {
        return other.sum(a, b);
    }

    public int sumWithOther(Calc1 other, int a, int b) {
        return other.plus(a, b);
    }
}
```
Then received test cases with the following test case among them:
```kotlin
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.*;

public class GeneratedMultiply_LargeNumbers_Test {

    @Test
    public void multiply_LargeNumbers_Test() {
        Calc calc = new Calc();
        int result = calc.multiply(1000000, 2000000);
        assertEquals(2000000000000L, result);
    }
}
```
Then sent a prompt via the `"Modify with LLM"` button containing **"Is not it an overflow of ints?"**; the LLM responded with an entire test suite. Thus the test suite was inserted into the code editor dedicated to a single test case:
```kotlin
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class GeneratedMultiply_LargeNumbers_Test {

    @Test
    public void multiply_PositiveNumbers_Test() {
        Calc calc = new Calc();
        int result = calc.multiply(2, 3);
        assertEquals(6, result);

    }

    @Test
    public void multiply_NegativeNumbers_Test() {
        Calc calc = new Calc();
        int result = calc.multiply(-2, -3);
        assertEquals(6, result);

    }

    @Test
    public void multiply_PositiveAndNegativeNumbers_Test() {
        Calc calc = new Calc();
        int result = calc.multiply(2, -3);
        assertEquals(-6, result);

    }

    @Test
    public void multiply_Zero_Test() {
        Calc calc = new Calc();
        int result = calc.multiply(0, 3);
        assertEquals(0, result);

    }

    @Test
    public void multiply_LargeNumbers_Test() {
        Calc calc = new Calc();
        int result = calc.multiply(1000000, 2000000);
        int expectedOverflow = (int) ((long) 1000000 * 2000000);
        assertEquals(expectedOverflow, result);

    }

}
```

**To Reproduce**
Steps to reproduce the behavior (it may not always be reproducible):
1. Select a class under test and request LLM test generation
2. Select any test case and use "Modify with LLM" asking a vague question (i.e., not giving an exact extraction)
3. LLM may respond with the entire test suite.

**Expected behavior**
Only an updated test case should be populated into the mini-editor.

**Screenshots**

https://github.com/JetBrains-Research/TestSpark/assets/47076189/12351158-8a31-43ad-b233-8305106884da

**Comment by Hello-zoka** [comment]
The main problem we face here is prompt modification of a 'lightweight' instrument, which doesn't include multiple checks and additional generations if some of the invariants we had after feedback-cycle generation were broken. #357 includes a prompt adjustment to reduce the amount of such problems, but it doesn't exclude it at all. This issue can be closed if we consider it the user's problem when such modification is incorrect(we have a history of modifications for this) or we have to make major reconstructing for this tool, probably using such approaches(does require major refactoring in **core** module):

- Implement some kind of feedback cycle to check all the invariants after prompt modification
- Adjust the feedback cycle to be able to make such modifications
- Provide more feedback to user after manual check of all invariants(also requires refactoring in main feedback cycle due to current architecture)

**Comment by Vladislav0Art** [comment]
> The main problem we face here is prompt modification of a 'lightweight' instrument, which doesn't include multiple checks and additional generations if some of the invariants we had after feedback-cycle generation were broken. #357 includes a prompt adjustment to reduce the amount of such problems, but it doesn't exclude it at all. This issue can be closed if we consider it the user's problem when such modification is incorrect(we have a history of modifications for this) or we have to make major reconstructing for this tool, probably using such approaches(does require major refactoring in **core** module):
> 
> * Implement some kind of feedback cycle to check all the invariants after prompt modification
> * Adjust the feedback cycle to be able to make such modifications
> * Provide more feedback to user after manual check of all invariants(also requires refactoring in main feedback cycle due to current architecture)

We can close this issue, as it is not worth the effort spent on the possible solutions; the profit is minimal.

CC: @pderakhshanfar @arksap2002
