### ISSUE TITLE
Incompatibility with current releases of IntelliJ (242.*)

### ISSUE THREAD

**Issue by PorfirioTramontana** [JetBrains-Research/TestSpark#395]
**Describe the bug**
The plug-in cannot be used under the most recent releases of Intellij IDEA and Android Studio

**To Reproduce**
1. Install the extension under IntelliJ IDEA

**Screenshots**
![image](https://github.com/user-attachments/assets/f1e199d0-4bef-4722-bdac-846866777591)

**Additional context**
IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4054M
Cores: 20
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.jetbrains.space (242.23339.11)
  com.intellij.ml.llm (242.23339.40)
  com.github.copilot (1.5.25.10)
Kotlin: 242.23339.11-IJ

**Comment by Vladislav0Art** [comment]
Hi! Thank you for the report! It was closed by #386. We are working on a release.

Feel free to re-open if you encounter any problems.
